
# Venture Context Config (reference-venture-example)
# Purpose: Inherit SoT/Prompts/Eval from portfolio; set venture defaults.

inherit:
  sot: ../../sot/context_schemas_v02.yaml
  prompts_dir: ../../prompts
  eval_dir: ../../eval

venture:
  id: 01JVNTRREFERENCEEXAMPLEID      # ULID placeholder
  slug: reference-venture-example
  name: "Reference Venture (Example)"
  default_zone: internal
  tags: [reference, example, venture]

retrieval:
  mode_profiles:
    planning:
      k_in: 30
      k_out: 8
    execution:
      k_in: 20
      k_out: 6

policies:
  zone_inheritance: strict           # see decisions/2025-10-17_zone-inheritance-policy_v01.md
  ttl_default_days: 21               # see decisions/2025-10-17_context-ttl-policy_v01.md
  citations_required: true

logging:
  actions_csv: ../../logs/context_actions.csv
